"""Initial Models

Revision ID: 0b3c5b59e181
Revises: 1b8ce9e471a2
Create Date: 2026-07-04 06:37:30.589793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b3c5b59e181'
down_revision: Union[str, None] = '1b8ce9e471a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('statement_uuid', sa.String(), nullable=False),
    sa.Column('fecha_operacion', sa.Date(), nullable=False),
    sa.Column('monto_absoluto', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('naturaleza', sa.String(length=10), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('concepto_bancario_original', sa.String(), nullable=False),
    sa.Column('referencia_numerica_limpia', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canonical_transactions_statement_uuid'), 'canonical_transactions', ['statement_uuid'], unique=False)
    op.create_table('canonical_xmls',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('uuid_cfdi', sa.String(), nullable=False),
    sa.Column('rfc_emisor', sa.String(length=13), nullable=False),
    sa.Column('rfc_receptor', sa.String(length=13), nullable=False),
    sa.Column('tipo_cfdi', sa.String(length=2), nullable=False),
    sa.Column('metodo_pago', sa.String(length=3), nullable=True),
    sa.Column('forma_pago', sa.String(length=3), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('estado_cancelacion', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canonical_xmls_rfc_emisor'), 'canonical_xmls', ['rfc_emisor'], unique=False)
    op.create_index(op.f('ix_canonical_xmls_rfc_receptor'), 'canonical_xmls', ['rfc_receptor'], unique=False)
    op.create_index(op.f('ix_canonical_xmls_uuid_cfdi'), 'canonical_xmls', ['uuid_cfdi'], unique=True)
    op.create_table('companies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rfc', sa.String(length=13), nullable=False),
    sa.Column('razon_social', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_rfc'), 'companies', ['rfc'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('tamanio_bytes', sa.Integer(), nullable=False),
    sa.Column('fecha_carga', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_hash_sha256'), 'documents', ['hash_sha256'], unique=True)
    op.create_table('document_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('storage_url', sa.String(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('fecha_version', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('mensaje', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_events_estado'), 'workflow_events', ['estado'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_events_estado'), table_name='workflow_events')
    op.drop_table('workflow_events')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_documents_hash_sha256'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_companies_rfc'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_canonical_xmls_uuid_cfdi'), table_name='canonical_xmls')
    op.drop_index(op.f('ix_canonical_xmls_rfc_receptor'), table_name='canonical_xmls')
    op.drop_index(op.f('ix_canonical_xmls_rfc_emisor'), table_name='canonical_xmls')
    op.drop_table('canonical_xmls')
    op.drop_index(op.f('ix_canonical_transactions_statement_uuid'), table_name='canonical_transactions')
    op.drop_table('canonical_transactions')
    # ### end Alembic commands ###
