"""Add persistence models phase 19

Revision ID: 2cdef6ea59d3
Revises: 0b3c5b59e181
Create Date: 2026-07-04 13:01:50.099722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cdef6ea59d3'
down_revision: Union[str, None] = '0b3c5b59e181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounting_proposals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_uuid', sa.String(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('es_cuadrada', sa.Boolean(), nullable=False),
    sa.Column('total_cargos', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_abonos', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('asientos', sa.JSON(), nullable=False),
    sa.Column('tipo_poliza', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('processing_run_id', sa.String(), nullable=True),
    sa.Column('workflow_event_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounting_proposals_processing_run_id'), 'accounting_proposals', ['processing_run_id'], unique=False)
    op.create_index(op.f('ix_accounting_proposals_source_uuid'), 'accounting_proposals', ['source_uuid'], unique=False)
    op.create_index(op.f('ix_accounting_proposals_tenant_id'), 'accounting_proposals', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_accounting_proposals_workflow_event_id'), 'accounting_proposals', ['workflow_event_id'], unique=False)
    op.create_table('conciliation_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_timestamp', sa.DateTime(), nullable=False),
    sa.Column('total_transactions_analyzed', sa.Integer(), nullable=False),
    sa.Column('total_xmls_analyzed', sa.Integer(), nullable=False),
    sa.Column('exact_matches_count', sa.Integer(), nullable=False),
    sa.Column('partial_matches_count', sa.Integer(), nullable=False),
    sa.Column('unmatched_transactions', sa.JSON(), nullable=False),
    sa.Column('unmatched_xmls', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('processing_run_id', sa.String(), nullable=True),
    sa.Column('workflow_event_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conciliation_results_processing_run_id'), 'conciliation_results', ['processing_run_id'], unique=False)
    op.create_index(op.f('ix_conciliation_results_workflow_event_id'), 'conciliation_results', ['workflow_event_id'], unique=False)
    op.create_table('match_candidates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conciliation_result_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('strategy_used', sa.String(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('partial_applied_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('partial_remaining_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('transaction_ids', sa.JSON(), nullable=False),
    sa.Column('xml_ids', sa.JSON(), nullable=False),
    sa.Column('explanations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('processing_run_id', sa.String(), nullable=True),
    sa.Column('workflow_event_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conciliation_result_id'], ['conciliation_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_candidates_processing_run_id'), 'match_candidates', ['processing_run_id'], unique=False)
    op.create_index(op.f('ix_match_candidates_workflow_event_id'), 'match_candidates', ['workflow_event_id'], unique=False)
    op.create_table('canonical_statements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_uuid', sa.String(), nullable=False),
    sa.Column('banco', sa.String(), nullable=False),
    sa.Column('cuenta', sa.String(), nullable=False),
    sa.Column('periodo_inicio', sa.Date(), nullable=False),
    sa.Column('periodo_fin', sa.Date(), nullable=False),
    sa.Column('fecha_corte', sa.Date(), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('saldo_inicial', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('saldo_final', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('processing_run_id', sa.String(), nullable=True),
    sa.Column('workflow_event_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_uuid'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canonical_statements_document_uuid'), 'canonical_statements', ['document_uuid'], unique=False)
    op.create_index(op.f('ix_canonical_statements_processing_run_id'), 'canonical_statements', ['processing_run_id'], unique=False)
    op.create_index(op.f('ix_canonical_statements_workflow_event_id'), 'canonical_statements', ['workflow_event_id'], unique=False)
    op.create_table('evidence_packages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('match_candidate_id', sa.String(), nullable=False),
    sa.Column('storage_url', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('is_compressed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('processing_run_id', sa.String(), nullable=True),
    sa.Column('workflow_event_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_candidate_id'], ['match_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_packages_processing_run_id'), 'evidence_packages', ['processing_run_id'], unique=False)
    op.create_index(op.f('ix_evidence_packages_workflow_event_id'), 'evidence_packages', ['workflow_event_id'], unique=False)
    op.create_table('sat_validation_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('xml_uuid', sa.String(), nullable=False),
    sa.Column('overall_status', sa.String(), nullable=False),
    sa.Column('rule_results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('processing_run_id', sa.String(), nullable=True),
    sa.Column('workflow_event_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['xml_uuid'], ['canonical_xmls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sat_validation_results_processing_run_id'), 'sat_validation_results', ['processing_run_id'], unique=False)
    op.create_index(op.f('ix_sat_validation_results_workflow_event_id'), 'sat_validation_results', ['workflow_event_id'], unique=False)
    op.create_index(op.f('ix_sat_validation_results_xml_uuid'), 'sat_validation_results', ['xml_uuid'], unique=False)
    op.add_column('canonical_transactions', sa.Column('concepto_original', sa.String(), nullable=False))
    op.add_column('canonical_transactions', sa.Column('referencia_bancaria_original', sa.String(), nullable=True))
    op.add_column('canonical_transactions', sa.Column('referencia_bancaria_limpia', sa.String(), nullable=True))
    op.add_column('canonical_transactions', sa.Column('clave_rastreo', sa.String(), nullable=True))
    op.add_column('canonical_transactions', sa.Column('numero_operacion', sa.String(), nullable=True))
    op.add_column('canonical_transactions', sa.Column('autorizacion', sa.String(), nullable=True))
    op.add_column('canonical_transactions', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('canonical_transactions', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('canonical_transactions', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('canonical_transactions', sa.Column('processing_run_id', sa.String(), nullable=True))
    op.add_column('canonical_transactions', sa.Column('workflow_event_id', sa.String(), nullable=True))
    op.add_column('canonical_transactions', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('canonical_transactions', sa.Column('status', sa.String(), nullable=False))
    op.add_column('canonical_transactions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_canonical_transactions_processing_run_id'), 'canonical_transactions', ['processing_run_id'], unique=False)
    op.create_index(op.f('ix_canonical_transactions_workflow_event_id'), 'canonical_transactions', ['workflow_event_id'], unique=False)
    op.create_foreign_key(None, 'canonical_transactions', 'canonical_statements', ['statement_uuid'], ['id'])
    op.drop_column('canonical_transactions', 'referencia_numerica_limpia')
    op.drop_column('canonical_transactions', 'concepto_bancario_original')
    op.add_column('canonical_xmls', sa.Column('document_uuid', sa.String(), nullable=True))
    op.add_column('canonical_xmls', sa.Column('impuestos_desglosados', sa.JSON(), nullable=True))
    op.add_column('canonical_xmls', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('canonical_xmls', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('canonical_xmls', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('canonical_xmls', sa.Column('processing_run_id', sa.String(), nullable=True))
    op.add_column('canonical_xmls', sa.Column('workflow_event_id', sa.String(), nullable=True))
    op.add_column('canonical_xmls', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('canonical_xmls', sa.Column('status', sa.String(), nullable=False))
    op.add_column('canonical_xmls', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_canonical_xmls_document_uuid'), 'canonical_xmls', ['document_uuid'], unique=False)
    op.create_index(op.f('ix_canonical_xmls_processing_run_id'), 'canonical_xmls', ['processing_run_id'], unique=False)
    op.create_index(op.f('ix_canonical_xmls_workflow_event_id'), 'canonical_xmls', ['workflow_event_id'], unique=False)
    op.create_foreign_key(None, 'canonical_xmls', 'documents', ['document_uuid'], ['id'])
    op.add_column('companies', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('companies', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('companies', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('processing_run_id', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('workflow_event_id', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('companies', sa.Column('status', sa.String(), nullable=False))
    op.add_column('companies', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_companies_processing_run_id'), 'companies', ['processing_run_id'], unique=False)
    op.create_index(op.f('ix_companies_workflow_event_id'), 'companies', ['workflow_event_id'], unique=False)
    op.add_column('document_versions', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('document_versions', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('document_versions', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('document_versions', sa.Column('processing_run_id', sa.String(), nullable=True))
    op.add_column('document_versions', sa.Column('workflow_event_id', sa.String(), nullable=True))
    op.add_column('document_versions', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('document_versions', sa.Column('status', sa.String(), nullable=False))
    op.add_column('document_versions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_document_versions_processing_run_id'), 'document_versions', ['processing_run_id'], unique=False)
    op.create_index(op.f('ix_document_versions_workflow_event_id'), 'document_versions', ['workflow_event_id'], unique=False)
    op.add_column('documents', sa.Column('fingerprint', sa.String(length=64), nullable=True))
    op.add_column('documents', sa.Column('subtipo_documento', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('fecha_documento', sa.Date(), nullable=True))
    op.add_column('documents', sa.Column('ejercicio', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('periodo', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('banco', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('cuenta', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('moneda', sa.String(length=3), nullable=True))
    op.add_column('documents', sa.Column('origen', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('estado_workflow', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('uuid_cfdi', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('referencia_bancaria', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('documents', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('processing_run_id', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('workflow_event_id', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('status', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_documents_banco'), 'documents', ['banco'], unique=False)
    op.create_index(op.f('ix_documents_company_id'), 'documents', ['company_id'], unique=False)
    op.create_index(op.f('ix_documents_cuenta'), 'documents', ['cuenta'], unique=False)
    op.create_index(op.f('ix_documents_ejercicio'), 'documents', ['ejercicio'], unique=False)
    op.create_index(op.f('ix_documents_estado_workflow'), 'documents', ['estado_workflow'], unique=False)
    op.create_index(op.f('ix_documents_fecha_documento'), 'documents', ['fecha_documento'], unique=False)
    op.create_index(op.f('ix_documents_fingerprint'), 'documents', ['fingerprint'], unique=True)
    op.create_index(op.f('ix_documents_periodo'), 'documents', ['periodo'], unique=False)
    op.create_index(op.f('ix_documents_processing_run_id'), 'documents', ['processing_run_id'], unique=False)
    op.create_index(op.f('ix_documents_referencia_bancaria'), 'documents', ['referencia_bancaria'], unique=False)
    op.create_index(op.f('ix_documents_tipo'), 'documents', ['tipo'], unique=False)
    op.create_index(op.f('ix_documents_uuid_cfdi'), 'documents', ['uuid_cfdi'], unique=False)
    op.create_index(op.f('ix_documents_workflow_event_id'), 'documents', ['workflow_event_id'], unique=False)
    op.add_column('workflow_events', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('workflow_events', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('workflow_events', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('workflow_events', sa.Column('processing_run_id', sa.String(), nullable=True))
    op.add_column('workflow_events', sa.Column('workflow_event_id', sa.String(), nullable=True))
    op.add_column('workflow_events', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('workflow_events', sa.Column('status', sa.String(), nullable=False))
    op.add_column('workflow_events', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_workflow_events_processing_run_id'), 'workflow_events', ['processing_run_id'], unique=False)
    op.create_index(op.f('ix_workflow_events_workflow_event_id'), 'workflow_events', ['workflow_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_events_workflow_event_id'), table_name='workflow_events')
    op.drop_index(op.f('ix_workflow_events_processing_run_id'), table_name='workflow_events')
    op.drop_column('workflow_events', 'deleted_at')
    op.drop_column('workflow_events', 'status')
    op.drop_column('workflow_events', 'version')
    op.drop_column('workflow_events', 'workflow_event_id')
    op.drop_column('workflow_events', 'processing_run_id')
    op.drop_column('workflow_events', 'created_by')
    op.drop_column('workflow_events', 'updated_at')
    op.drop_column('workflow_events', 'created_at')
    op.drop_index(op.f('ix_documents_workflow_event_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_uuid_cfdi'), table_name='documents')
    op.drop_index(op.f('ix_documents_tipo'), table_name='documents')
    op.drop_index(op.f('ix_documents_referencia_bancaria'), table_name='documents')
    op.drop_index(op.f('ix_documents_processing_run_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_periodo'), table_name='documents')
    op.drop_index(op.f('ix_documents_fingerprint'), table_name='documents')
    op.drop_index(op.f('ix_documents_fecha_documento'), table_name='documents')
    op.drop_index(op.f('ix_documents_estado_workflow'), table_name='documents')
    op.drop_index(op.f('ix_documents_ejercicio'), table_name='documents')
    op.drop_index(op.f('ix_documents_cuenta'), table_name='documents')
    op.drop_index(op.f('ix_documents_company_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_banco'), table_name='documents')
    op.drop_column('documents', 'deleted_at')
    op.drop_column('documents', 'status')
    op.drop_column('documents', 'version')
    op.drop_column('documents', 'workflow_event_id')
    op.drop_column('documents', 'processing_run_id')
    op.drop_column('documents', 'created_by')
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'created_at')
    op.drop_column('documents', 'referencia_bancaria')
    op.drop_column('documents', 'uuid_cfdi')
    op.drop_column('documents', 'estado_workflow')
    op.drop_column('documents', 'origen')
    op.drop_column('documents', 'moneda')
    op.drop_column('documents', 'cuenta')
    op.drop_column('documents', 'banco')
    op.drop_column('documents', 'periodo')
    op.drop_column('documents', 'ejercicio')
    op.drop_column('documents', 'fecha_documento')
    op.drop_column('documents', 'subtipo_documento')
    op.drop_column('documents', 'fingerprint')
    op.drop_index(op.f('ix_document_versions_workflow_event_id'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_processing_run_id'), table_name='document_versions')
    op.drop_column('document_versions', 'deleted_at')
    op.drop_column('document_versions', 'status')
    op.drop_column('document_versions', 'version')
    op.drop_column('document_versions', 'workflow_event_id')
    op.drop_column('document_versions', 'processing_run_id')
    op.drop_column('document_versions', 'created_by')
    op.drop_column('document_versions', 'updated_at')
    op.drop_column('document_versions', 'created_at')
    op.drop_index(op.f('ix_companies_workflow_event_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_processing_run_id'), table_name='companies')
    op.drop_column('companies', 'deleted_at')
    op.drop_column('companies', 'status')
    op.drop_column('companies', 'version')
    op.drop_column('companies', 'workflow_event_id')
    op.drop_column('companies', 'processing_run_id')
    op.drop_column('companies', 'created_by')
    op.drop_column('companies', 'updated_at')
    op.drop_column('companies', 'created_at')
    op.drop_constraint(None, 'canonical_xmls', type_='foreignkey')
    op.drop_index(op.f('ix_canonical_xmls_workflow_event_id'), table_name='canonical_xmls')
    op.drop_index(op.f('ix_canonical_xmls_processing_run_id'), table_name='canonical_xmls')
    op.drop_index(op.f('ix_canonical_xmls_document_uuid'), table_name='canonical_xmls')
    op.drop_column('canonical_xmls', 'deleted_at')
    op.drop_column('canonical_xmls', 'status')
    op.drop_column('canonical_xmls', 'version')
    op.drop_column('canonical_xmls', 'workflow_event_id')
    op.drop_column('canonical_xmls', 'processing_run_id')
    op.drop_column('canonical_xmls', 'created_by')
    op.drop_column('canonical_xmls', 'updated_at')
    op.drop_column('canonical_xmls', 'created_at')
    op.drop_column('canonical_xmls', 'impuestos_desglosados')
    op.drop_column('canonical_xmls', 'document_uuid')
    op.add_column('canonical_transactions', sa.Column('concepto_bancario_original', sa.VARCHAR(), nullable=False))
    op.add_column('canonical_transactions', sa.Column('referencia_numerica_limpia', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'canonical_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_canonical_transactions_workflow_event_id'), table_name='canonical_transactions')
    op.drop_index(op.f('ix_canonical_transactions_processing_run_id'), table_name='canonical_transactions')
    op.drop_column('canonical_transactions', 'deleted_at')
    op.drop_column('canonical_transactions', 'status')
    op.drop_column('canonical_transactions', 'version')
    op.drop_column('canonical_transactions', 'workflow_event_id')
    op.drop_column('canonical_transactions', 'processing_run_id')
    op.drop_column('canonical_transactions', 'created_by')
    op.drop_column('canonical_transactions', 'updated_at')
    op.drop_column('canonical_transactions', 'created_at')
    op.drop_column('canonical_transactions', 'autorizacion')
    op.drop_column('canonical_transactions', 'numero_operacion')
    op.drop_column('canonical_transactions', 'clave_rastreo')
    op.drop_column('canonical_transactions', 'referencia_bancaria_limpia')
    op.drop_column('canonical_transactions', 'referencia_bancaria_original')
    op.drop_column('canonical_transactions', 'concepto_original')
    op.drop_index(op.f('ix_sat_validation_results_xml_uuid'), table_name='sat_validation_results')
    op.drop_index(op.f('ix_sat_validation_results_workflow_event_id'), table_name='sat_validation_results')
    op.drop_index(op.f('ix_sat_validation_results_processing_run_id'), table_name='sat_validation_results')
    op.drop_table('sat_validation_results')
    op.drop_index(op.f('ix_evidence_packages_workflow_event_id'), table_name='evidence_packages')
    op.drop_index(op.f('ix_evidence_packages_processing_run_id'), table_name='evidence_packages')
    op.drop_table('evidence_packages')
    op.drop_index(op.f('ix_canonical_statements_workflow_event_id'), table_name='canonical_statements')
    op.drop_index(op.f('ix_canonical_statements_processing_run_id'), table_name='canonical_statements')
    op.drop_index(op.f('ix_canonical_statements_document_uuid'), table_name='canonical_statements')
    op.drop_table('canonical_statements')
    op.drop_index(op.f('ix_match_candidates_workflow_event_id'), table_name='match_candidates')
    op.drop_index(op.f('ix_match_candidates_processing_run_id'), table_name='match_candidates')
    op.drop_table('match_candidates')
    op.drop_index(op.f('ix_conciliation_results_workflow_event_id'), table_name='conciliation_results')
    op.drop_index(op.f('ix_conciliation_results_processing_run_id'), table_name='conciliation_results')
    op.drop_table('conciliation_results')
    op.drop_index(op.f('ix_accounting_proposals_workflow_event_id'), table_name='accounting_proposals')
    op.drop_index(op.f('ix_accounting_proposals_tenant_id'), table_name='accounting_proposals')
    op.drop_index(op.f('ix_accounting_proposals_source_uuid'), table_name='accounting_proposals')
    op.drop_index(op.f('ix_accounting_proposals_processing_run_id'), table_name='accounting_proposals')
    op.drop_table('accounting_proposals')
    # ### end Alembic commands ###
