from enum import Enum

class WorkflowState(str, Enum):
    RECEIVED = "RECEIVED"
    STORED = "STORED"
    CLASSIFIED = "CLASSIFIED"
    PARSED = "PARSED"
    NORMALIZED = "NORMALIZED"
    VALIDATED = "VALIDATED"
    READY_FOR_CONCILIATION = "READY_FOR_CONCILIATION"
    FAILED = "FAILED"
    REQUIRES_REVIEW = "REQUIRES_REVIEW"
